backend:
  name: github
  repo: bascanada/soundboard-template # User's repo
  branch: main
  base_url: https://kessequidit.bascanada.org # or your deployed domain
  auth_endpoint: /admin/oauth/auth
  logo_url: /favicon.png

media_folder: "static/media"
public_folder: "/media"

collections:
  - name: "config"
    label: "Configuration"
    files:
      - name: "site"
        label: "Site Settings"
        file: "config/site.json"
        fields:
          - {label: "Site Title", name: "title", widget: "string"}
          - {label: "Description", name: "description", widget: "string"}
          - {label: "Author", name: "author", widget: "string"}
          - {label: "Favicon", name: "favicon", widget: "image"}
          - {label: "Keywords", name: "keywords", widget: "list"}
          - name: "pwa"
            label: "PWA Settings"
            widget: "object"
            fields:
              - {label: "App Name", name: "name", widget: "string"}
              - {label: "Short Name", name: "short_name", widget: "string"}
              - {label: "Theme Color", name: "theme_color", widget: "color"}
              - {label: "Background Color", name: "background_color", widget: "color"}
      - name: "clips"
        label: "Clips Database"
        file: "config/clips.json"
        fields:
          - label: "Video Sources"
            name: "sources"
            widget: "list"
            fields:
              - {label: "YouTube URL", name: "videoUrl", widget: "string"}
              - label: "Clips"
                name: "clips"
                widget: "list"
                fields:
                  - {label: "Title", name: "title", widget: "string"}
                  - {label: "Category", name: "category", widget: "string"}
                  - {label: "Start Time", name: "start", widget: "string", hint: "Format: 00:00 or 00:00.00", pattern: ['^(\d+(\.\d+)?|(\d{1,2}:)?\d{1,2}:\d{2}(\.\d+)?)$', "Invalid format. Use MM:SS, HH:MM:SS, or Seconds (e.g. 1:30, 90)"]}
                  - {label: "End Time", name: "end", widget: "string", hint: "Format: 00:00 or 00:00.00", pattern: ['^(\d+(\.\d+)?|(\d{1,2}:)?\d{1,2}:\d{2}(\.\d+)?)$', "Invalid format. Use MM:SS, HH:MM:SS, or Seconds (e.g. 1:30, 90)"]}
                  - {label: "Includes Video?", name: "video", widget: "boolean", default: true, required: false}
                  - {label: "Zoom Scale", name: "scale", widget: "number", default: 1.0, value_type: "float", required: false, hint: "1.0 = No Zoom, 1.25 = 125%"}
